- name: APP Execute migrations
  command: "node ./node_modules/sequelize-cli/lib/sequelize db:migrate"
  args:
    chdir: "{{ appdir }}"
  become: yes
  become_user: "{{ userdba }}"
  become_method: sudo
